if: type IN (api, cron)
language: python
dist: trusty
sudo: true

install: 
  - sudo apt install sshpass -y
  - curl -s https://install.zerotier.com/ | sudo bash

jobs:
  include:
  # - stage: build images
  #   script: echo "Building images"
      
  # - stage: update environment
  #   script: echo "Updating environment"

  - stage: ovc acl tests
    script: bash scripts/travis/travis.sh --run-test acl ${acl_tests_path}
    after_script: bash scripts/travis/travis.sh --push-result acl

  - stage: ovc acl tests
    script: bash scripts/travis/travis.sh --run-test ovc ${ovc_tests_path}
    after_script: bash scripts/travis/travis.sh --push-result ovc

  - stage: portal tests
    script: bash scripts/travis/travis.sh --run-test portal ${portal_tests_path}
    after_script: bash scripts/travis/travis.sh --push-result portal