#!/bin/bash
set -e
sudo modprobe fuse
sudo modprobe openvswitch
sudo modprobe kvm
sudo modprobe tun
if [ -z "$1" ]; then
    echo "Need node name"
    exit 1
fi
node=$1

echoerr() { echo "$@" 1>&2; }

function createdev() {
    filename="$HOME/.cache/loopdevs/${node}-${1}"
    devname="${node}-${1}"
    devsize=$2
    created="0"
    if [ ! -e $devname ]; then
        echoerr Create devices
        truncate -s $devsize $filename
        created="1"
    fi
    if ! losetup | grep $devname > /dev/null; then
        echoerr Loop devices
        sudo losetup -P -f $filename
    fi
    dev=$(losetup -a | grep $devname | cut -d ':' -f 1)
    if [[ $created == "0" ]]; then
        echo $dev
        return 0
    fi
    if [ ! -e "${dev}p1" ]; then
        echoerr Create partitions
        sudo parted -s -a optimal $dev mklabel gpt -- mkpart primary ext4 1 -1 &> /dev/null
        echoerr Create fs
        sudo mkfs.ext4 -L $devname "${dev}p1" &> /dev/null
    fi
    echo $dev

}

mkdir -p $HOME/.cache/loopdevs/
createdev db 4GB
createdev asd 200GB
