#!/bin/bash
#make nodes on
function dupdev() {
    dev=$1
    major=$(ls -l $dev | awk '{print $5}' | cut -d ',' -f 1)
    minor=$(ls -l $dev | awk '{print $6}')
    prefix=$(ls -l $dev)
    devtype=${prefix::1}
    mknod "${LXC_ROOTFS_MOUNT}${dev}" $devtype $major $minor
}

mkdir -p "${LXC_ROOTFS_MOUNT}/dev/net"
dupdev /dev/net/tun
dupdev /dev/fuse
dupdev /dev/kvm
for dev in /dev/loop*; do
  dupdev $dev
done
