#!/bin/bash
set -e
source "$(dirname $(readlink -f $0))/_functions"

cp /etc/hosts /etc/hosts.bak
umount /etc/hosts || true
cp /etc/hosts.bak /etc/hosts
installovsrepo
apt-get install -y iproute2 net-tools rsyslog sudo udev

red="/etc/systemd/system/redis-server.service.d/"
mkdir -p $red
echo '[Service]' > $red/redis.override.conf
echo 'PrivateDevices=no' >> $red/redis.override.conf

apt-get install -y volumedriver-no-dedup-server
apt-get install -y openvstorage-hc
systemctl enable cron
systemctl start cron
IPSUFFIX=$(($(hostname -s | sed "s/[^0-9]//g") + 9))

cat << EOF > /opt/asd-manager/config/preconfig.json
{
    "asdmanager": {
        "api_ip": "172.17.1.$IPSUFFIX", 
        "asd_start_port": 8600, 
        "asd_ips": [
            "172.17.1.10"
        ], 
        "api_port": 8500
    }
}
EOF
cat << EOF > /opt/OpenvStorage/config/preconfig.json
{"setup": {                    
  "cluster_ip": "172.17.1.$IPSUFFIX", 
  "enable_heartbeats": true,   
  "external_config": null,     
  "logging_target": null,      
  "master_ip": "172.17.1.$IPSUFFIX",  
  "master_password": null,     
  "node_type": "master",       
  "rdma": false,               
  "rollback": null             
}}                             
EOF
ovs setup
installjs
ays install -n cb_storagedriver_aio --hrdseed /opt/code/github/0-complexity/openvcloud/scripts/dev/localnode/cfg/node.hrd
ays install -n cb_storagenode_aio --hrdseed /opt/code/github/0-complexity/openvcloud/scripts/dev/localnode/cfg/node.hrd
jspython /opt/code/github/0-complexity/openvcloud/scripts/ovs/alba-create-user.py
jspython /opt/code/github/0-complexity/openvcloud/scripts/dev/localnode/setupovs.py
