#!/bin/bash
set -e
source "$(dirname $(readlink -f $0))/_functions"

installovsrepo
installjs
ays install -n cb_cpunode_aio --hrdseed /opt/code/github/0-complexity/openvcloud/scripts/dev/localnode/cfg/node.hrd
if ! grep "^host_uuid" /etc/libvirt/libvirtd.conf > /dev/null; then
    echo "host_uuid = \"$(uuidgen)\"" >> /etc/libvirt/libvirtd.conf
fi
systemctl enable libvirt-bin
systemctl start libvirt-bin
systemctl enable virtlogd
systemctl start virtlogd
echo "
<network>
       <name>gw_mgmt</name>
       <forward mode='bridge'/>
       <bridge name='gw_mgmt'/>
       <virtualport type='openvswitch'/>
   </network>
" > /tmp/net.xml
virsh net-define /tmp/net.xml || true
virsh net-autostart gw_mgmt || true
virsh net-start gw_mgmt || true
