class Machine(object):
    """
    Define possible machine model status
    """
    DESTROYED = 'DESTROYED'
    DESTROYING = 'DESTROYING'
    PAUSED = 'PAUSED'
    DELETED = 'DELETED'
    ERROR = 'ERROR'
    RUNNING = 'RUNNING'
    HALTED = 'HALTED'
    INVALID_STATES = [DESTROYED, DELETED, ERROR, DESTROYING]
    NON_CONSUMING_STATES = [DESTROYED, DELETED, ERROR, HALTED]
    VALID_STATES = [PAUSED, HALTED, RUNNING]
    UP_STATES = [RUNNING, PAUSED]

class Cloudspace(object):
    VIRTUAL = 'VIRTUAL'
    DEPLOYING = 'DEPLOYING'
    DESTROYED = 'DESTROYED'
    DEPLOYED = 'DEPLOYED'
    DESTROYING = 'DESTROYING'
    DISABLED = 'DISABLED'

class Account(object):
    DESTROYED = 'DESTROYED'
    DESTROYING = 'DESTROYING'
    CONFIRMED = 'CONFIRMED'
    DISABLED = 'DISABLED'
    
