class Machine(object):
    """
    Define possible machine model status
    """
    DESTROYED = 'DESTROYED'
    DESTROYING = 'DESTROYING'
    PAUSED = 'PAUSED'
    DELETED = 'DELETED'
    ERROR = 'ERROR'
    RUNNING = 'RUNNING'
    HALTED = 'HALTED'
    MIGRATING = 'MIGRATING'
    INVALID_STATES = [DESTROYED, DELETED, ERROR, DESTROYING]
    NON_CONSUMING_STATES = [DESTROYED, DELETED, ERROR, HALTED]
    VALID_STATES = [PAUSED, HALTED, RUNNING, MIGRATING]
    UP_STATES = [RUNNING, PAUSED]

class Cloudspace(object):
    VIRTUAL = 'VIRTUAL'
    DEPLOYING = 'DEPLOYING'
    DESTROYED = 'DESTROYED'
    DEPLOYED = 'DEPLOYED'
    DESTROYING = 'DESTROYING'
    MIGRATING = 'MIGRATING'
    DISABLED = 'DISABLED'
    DELETED = 'DELETED'
    INVALID_STATES = [DESTROYED, DELETED]

class Account(object):
    DESTROYED = 'DESTROYED'
    DESTROYING = 'DESTROYING'
    CONFIRMED = 'CONFIRMED'
    DISABLED = 'DISABLED'
    DELETED = 'DELETED'
    INVALID_STATES = [DESTROYED, DESTROYING, DELETED]
    
class Disk(object):
    ASSIGNED = 'ASSIGNED'
    MODELED = 'MODELED'
    CREATING = 'CREATING'
    CREATED = 'CREATED'
    DESTROYED = 'DESTROYED'
    DELETED = 'DELETED'
    TOBEDELETED = 'TOBEDELETED'
    INVALID_STATES = [DESTROYED, TOBEDELETED, DELETED]

class Image(object):
    CREATED = 'CREATED'
    CREATING = 'CREATING'
    DESTROYED = 'DESTROYED'
    DELETED = 'DELETED'
    DISABLED = 'DISABLED'
    INVALID_STATES = [DESTROYED, DELETED]
