#!/bin/bash
sudo modprobe fuse
sudo modprobe openvswitch
sudo modprobe kvm
sudo modprobe tun
node=$1

echoerr() { echo "$@" 1>&2; }

function createdev() {
    devname=$1
    devsize=$2
    if [ ! -e $devname ]; then
        echoerr Create devices
        truncate -s $devsize $devname
    fi
    if ! losetup | grep $devname > /dev/null; then
        echoerr Loop devices
        sudo losetup -P -f $devname
    fi
    dev=$(losetup -a | grep $devname | cut -d ':' -f 1)
    if [ ! -e "${dev}p1" ]; then
        echoerr Create partitions
        sudo parted -s -a optimal $dev mklabel msdos -- mkpart primary ext4 1 -1 >&2
        echoerr Create fs
        sudo mkfs.ext4 "${dev}p1" >&2
    fi
    echo $dev

}

function rexec () {
    ssh "root@${node}" $@
}

#make nodes on
function dupdev() {
    dev=$1
    major=$(ls -l $dev | awk '{print $5}' | cut -d ',' -f 1)
    minor=$(ls -l $dev | awk '{print $6}')
    prefix=$(ls -l $dev)
    devtype=${prefix::1}
    rexec rm $dev
    rexec mknod $dev $devtype $major $minor
}

function setupdev() {
    name=$1
    size=$2
    devname=$(createdev "${node}_${name}" $size)
    dupdev "${devname}"
    dupdev "${devname}p1"
    rexec udevadm test "/sys/block/${devname}/${devname}p1"

    rexec mkdir /mnt/$name
    rexec mount "${devname}p1" /mnt/$name
}

function setupdevnomount() {
    name=$1
    size=$2
    devname=$(createdev "${node}_${name}" $size)
    dupdev "${devname}"
    dupdev "${devname}p1"
    rexec udevadm test "/sys/block/${devname}p1"
}


echo mknod
rexec mkdir /dev/net
dupdev /dev/net/tun
dupdev /dev/fuse
dupdev /dev/kvm

setupdev cache 4GB
setupdev db 4GB
setupdevnomount adb 200GB

rexec chmod 777 /dev/kvm
rexec ip l s vxbackend mtu 2000
rexec ovs-vsctl add-port backplane1 public-0 tag=0 -- set Interface public-0 type=patch options:peer=backplane1-0
rexec ovs-vsctl add-port public backplane1-0 -- set Interface backplane1-0 type=patch options:peer=public-0
