#!/bin/bash
ip l s vxbackend mtu 2000
ovs-vsctl add-port backplane1 vxbackend-200 tag=200 -- set Interface vxbackend-200 type=patch options:peer=backplane1-200
ovs-vsctl add-port backplane1 public-0 tag=0 -- set Interface public-0 type=patch options:peer=backplane1-0
